|  |  |
| - | - |
| ![Netflix-Device-Collage](Netflix-Device-Collage.jpg) | Netflix. What started in 1997 as a DVD rental service has since exploded into one of the largest entertainment and media companies. _You work for a production company that specializes in nostalgic styles. You want to do some research on movies released in the 1990's. You'll delve into Netflix data and perform exploratory data analysis to better understand this awesome movie decade._ You have been supplied with the dataset `netflix_data.csv`. |

In [ ]:
import pandas as pd

# read in data as a dataframe
netflix_df = pd.read_csv("netflix_data.csv")

netflix_df.head()

  show_id  ...             genre
0      s2  ...            Dramas
1      s3  ...     Horror Movies
2      s4  ...            Action
3      s5  ...            Dramas
4      s6  ...  International TV

[5 rows x 11 columns]

In [5]:
# filter the dataframe for movies released between 1990 and 1999
movies_90s = netflix_df[(netflix_df['type'] == 'Movie') & 
                        (netflix_df['release_year'] >= 1990) & 
                        (netflix_df['release_year'] <= 1999)]
movies_90s.head(10)

    show_id   type  ...                                        description     genre
6        s8  Movie  ...  After one of his high school students attacks ...    Dramas
118    s167  Movie  ...  At the center of this engrossing melodrama is ...    Dramas
145    s211  Movie  ...  After a run-in with Richard Grieco, dimwits Do...  Comedies
167    s239  Movie  ...  When a philandering club promoter sets out to ...  Comedies
194    s274  Movie  ...  Raised by a kindly thief, orphaned Jimmy goes ...    Dramas
240    s344  Movie  ...  A boy grows up to become a gangster in pursuit...    Dramas
315    s456  Movie  ...  While struggling to endure his tightly wound w...    Dramas
320    s467  Movie  ...  A neo-Nazi gets sent to prison for murder and ...    Dramas
333    s487  Movie  ...  Fievel and his family head west for what turns...  Children
334    s488  Movie  ...  When a monster goes on a mouse-napping spree i...  Children

[10 rows x 11 columns]

In [56]:
# prepped lists
short = []
standard = []

# loop through rows using .iterrows()
for index, row in movies_90s.iterrows():
    if row['duration'] < 90 and row['genre'] == 'Action':
        short.append(1)
    else:
        standard.append(1)

short_movie_count = sum(short)
standard_movie_count = sum(standard)

# use formatted strings for the output
print("Filtering complete.")
print(f"Short movies: {short_movie_count}")
print(f"Standard movies: {standard_movie_count}")

Filtering complete.
Short movies: 7
Standard movies: 176

In [57]:
# find the most frequent duration
duration = int(movies_90s['duration'].mode())

print(f"The most frequent movie time in the 90s was {duration} minutes.")

The most frequent movie time in the 90s was 94 minutes.